name: Basic Migration

on:
  push:
    branches: [main]

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Alembic Migration
        uses: sudzxd/alembic-deploy-action@v1
        with:
          database-url: ${{ secrets.DATABASE_URL }}
